fix: added error message for missing CVEs
project-zot/zot pull request #1085
Opened 2022-12-23 12:42 UTC by aokirisaki

Signed-off-by: Ana-Roberta Lisca <ana.kagome@yahoo.com>

**What type of PR is this?**

**Which issue does this PR fix**:
#803 

**What does this PR do / Why do we need it**:

**If an issue # is not available please add repro steps and logs showing the issue**:

**Testing done on this change**:

**Automation added to e2e**:

**Will this break upgrades or downgrades?**

**Does this PR introduce any user-facing change?**:

```release-note

```

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2022-12-23 13:26 UTC, andaaron requested changes

2022-12-23 13:26 UTC, andaaron commented on errors/errors.go
> +	ErrCVENotFound             = errors.New("CVE: no CVE found for image")
We shouldn't have such an error. Having no CVEs is a good thing.
And I also think this should be handled on ZLI side. It's a matter of how we present the results to the user.

2022-12-23 19:32 UTC, rchincha commented
rebase and update linting

2023-01-10 18:46 UTC, andaaron reviewed
Please add a comment with an example of the command, and command output.

2023-01-11 09:28 UTC, aokirisaki commented
> Please add a comment with an example of the command, and command output.

Here is an example output:
```
$ bin/zli-linux-amd64 cve config-multiple-cve5000 --image busybox:latest
No CVEs found for image
```

2023-01-11 09:33 UTC, andaaron approved these changes

2023-01-11 23:02 UTC, rchincha approved these changes
lgtm

2023-01-11 23:02 UTC, merged